// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chat.community.proto

package msg

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MessageSend
// @Function
// @Return: UserMessage
type CommunitySendMessage struct {
	RandomID   int64            `protobuf:"varint,1,req,name=RandomID" json:"RandomID"`
	Peer       *InputPeer       `protobuf:"bytes,2,req,name=Peer" json:"Peer,omitempty"`
	Body       string           `protobuf:"bytes,5,req,name=Body" json:"Body"`
	ReplyTo    int64            `protobuf:"varint,6,opt,name=ReplyTo" json:"ReplyTo"`
	ClearDraft bool             `protobuf:"varint,7,opt,name=ClearDraft" json:"ClearDraft"`
	Entities   []*MessageEntity `protobuf:"bytes,8,rep,name=Entities" json:"Entities,omitempty"`
}

func (m *CommunitySendMessage) Reset()         { *m = CommunitySendMessage{} }
func (m *CommunitySendMessage) String() string { return proto.CompactTextString(m) }
func (*CommunitySendMessage) ProtoMessage()    {}
func (*CommunitySendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49ab5d4c11d6137, []int{0}
}
func (m *CommunitySendMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommunitySendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommunitySendMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommunitySendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunitySendMessage.Merge(m, src)
}
func (m *CommunitySendMessage) XXX_Size() int {
	return m.Size()
}
func (m *CommunitySendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunitySendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommunitySendMessage proto.InternalMessageInfo

func (m *CommunitySendMessage) GetRandomID() int64 {
	if m != nil {
		return m.RandomID
	}
	return 0
}

func (m *CommunitySendMessage) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *CommunitySendMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CommunitySendMessage) GetReplyTo() int64 {
	if m != nil {
		return m.ReplyTo
	}
	return 0
}

func (m *CommunitySendMessage) GetClearDraft() bool {
	if m != nil {
		return m.ClearDraft
	}
	return false
}

func (m *CommunitySendMessage) GetEntities() []*MessageEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

// MessageSendMedia
// @Function
// @Return: UserMessage
type CommunitySendMedia struct {
	RandomID   int64          `protobuf:"varint,1,req,name=RandomID" json:"RandomID"`
	Peer       *InputPeer     `protobuf:"bytes,2,req,name=Peer" json:"Peer,omitempty"`
	MediaType  InputMediaType `protobuf:"varint,3,req,name=MediaType,enum=msg.InputMediaType" json:"MediaType"`
	MediaData  []byte         `protobuf:"bytes,4,req,name=MediaData" json:"MediaData"`
	ReplyTo    int64          `protobuf:"varint,5,opt,name=ReplyTo" json:"ReplyTo"`
	ClearDraft bool           `protobuf:"varint,6,opt,name=ClearDraft" json:"ClearDraft"`
}

func (m *CommunitySendMedia) Reset()         { *m = CommunitySendMedia{} }
func (m *CommunitySendMedia) String() string { return proto.CompactTextString(m) }
func (*CommunitySendMedia) ProtoMessage()    {}
func (*CommunitySendMedia) Descriptor() ([]byte, []int) {
	return fileDescriptor_c49ab5d4c11d6137, []int{1}
}
func (m *CommunitySendMedia) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommunitySendMedia) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommunitySendMedia.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommunitySendMedia) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunitySendMedia.Merge(m, src)
}
func (m *CommunitySendMedia) XXX_Size() int {
	return m.Size()
}
func (m *CommunitySendMedia) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunitySendMedia.DiscardUnknown(m)
}

var xxx_messageInfo_CommunitySendMedia proto.InternalMessageInfo

func (m *CommunitySendMedia) GetRandomID() int64 {
	if m != nil {
		return m.RandomID
	}
	return 0
}

func (m *CommunitySendMedia) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *CommunitySendMedia) GetMediaType() InputMediaType {
	if m != nil {
		return m.MediaType
	}
	return InputMediaTypeEmpty
}

func (m *CommunitySendMedia) GetMediaData() []byte {
	if m != nil {
		return m.MediaData
	}
	return nil
}

func (m *CommunitySendMedia) GetReplyTo() int64 {
	if m != nil {
		return m.ReplyTo
	}
	return 0
}

func (m *CommunitySendMedia) GetClearDraft() bool {
	if m != nil {
		return m.ClearDraft
	}
	return false
}

func init() {
	proto.RegisterType((*CommunitySendMessage)(nil), "msg.CommunitySendMessage")
	proto.RegisterType((*CommunitySendMedia)(nil), "msg.CommunitySendMedia")
}

func init() { proto.RegisterFile("chat.community.proto", fileDescriptor_c49ab5d4c11d6137) }

var fileDescriptor_c49ab5d4c11d6137 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xb1, 0x6e, 0xea, 0x30,
	0x14, 0x86, 0xe3, 0x24, 0x40, 0x30, 0x57, 0xe8, 0xca, 0x97, 0xc1, 0x42, 0x57, 0xbe, 0x56, 0x74,
	0x07, 0x2f, 0x0d, 0x12, 0x4b, 0x77, 0xa0, 0x03, 0x43, 0xa5, 0x2a, 0xe5, 0x05, 0x0c, 0x31, 0x21,
	0x12, 0x89, 0xa3, 0xc4, 0x19, 0xf2, 0x16, 0x7d, 0x2c, 0x46, 0xc6, 0x4e, 0x55, 0x0b, 0x6b, 0x5f,
	0xa1, 0x52, 0x85, 0x09, 0x81, 0x56, 0x95, 0xba, 0x74, 0xcb, 0xf9, 0xce, 0x97, 0x5f, 0x3e, 0x3f,
	0xec, 0x2d, 0x56, 0x5c, 0x79, 0x0b, 0x19, 0xc7, 0x45, 0x12, 0xa9, 0xd2, 0x4b, 0x33, 0xa9, 0x24,
	0xb2, 0xe2, 0x3c, 0xec, 0xff, 0x5e, 0xc8, 0x4c, 0x78, 0xaa, 0x4c, 0x45, 0x7e, 0xc4, 0xfd, 0xab,
	0x30, 0x52, 0xab, 0x62, 0x7e, 0xd0, 0x07, 0xa1, 0x0c, 0xe5, 0x40, 0xe3, 0x79, 0xb1, 0xd4, 0x93,
	0x1e, 0xf4, 0xd7, 0x51, 0x77, 0x5f, 0x01, 0xec, 0x8d, 0x4f, 0xc9, 0xf7, 0x22, 0x09, 0x6e, 0x45,
	0x9e, 0xf3, 0x50, 0x20, 0x0a, 0x1d, 0x9f, 0x27, 0x81, 0x8c, 0xa7, 0x13, 0x0c, 0xa8, 0xc9, 0xac,
	0x91, 0xbd, 0x79, 0xfa, 0x67, 0xf8, 0x35, 0x45, 0x2e, 0xb4, 0xef, 0x84, 0xc8, 0xb0, 0x49, 0x4d,
	0xd6, 0x19, 0x76, 0xbd, 0x38, 0x0f, 0xbd, 0x69, 0x92, 0x16, 0xea, 0x40, 0x7d, 0xbd, 0x43, 0x18,
	0xda, 0x23, 0x19, 0x94, 0xb8, 0x41, 0x4d, 0xd6, 0xae, 0x12, 0x34, 0x41, 0x04, 0xb6, 0x7c, 0x91,
	0xae, 0xcb, 0x99, 0xc4, 0x4d, 0x0a, 0xea, 0xf8, 0x13, 0x44, 0xff, 0x21, 0x1c, 0xaf, 0x05, 0xcf,
	0x26, 0x19, 0x5f, 0x2a, 0xdc, 0xa2, 0x80, 0x39, 0x95, 0x72, 0xc1, 0x91, 0x07, 0x9d, 0x9b, 0x44,
	0x45, 0x2a, 0x12, 0x39, 0x76, 0xa8, 0xc5, 0x3a, 0x43, 0xa4, 0xdf, 0x51, 0x5d, 0xa1, 0x77, 0xa5,
	0x5f, 0x3b, 0xee, 0x1b, 0x80, 0xe8, 0xd3, 0xb9, 0x41, 0xc4, 0x7f, 0xe8, 0xd8, 0x6b, 0xd8, 0xd6,
	0x71, 0xb3, 0x32, 0x15, 0xd8, 0xa2, 0x26, 0xeb, 0x0e, 0xff, 0x9c, 0xc5, 0x7a, 0x55, 0x65, 0x9f,
	0x5d, 0xe4, 0x56, 0x3f, 0x4e, 0xb8, 0xe2, 0xd8, 0xa6, 0x26, 0xfb, 0xf5, 0xc1, 0x39, 0xe0, 0xcb,
	0xbe, 0x1a, 0xdf, 0xf7, 0xd5, 0xfc, 0xba, 0xaf, 0xd1, 0xdf, 0xed, 0x0b, 0x31, 0x36, 0x3b, 0x02,
	0xb6, 0x3b, 0x02, 0x9e, 0x77, 0x04, 0x3c, 0xec, 0x89, 0xb1, 0xdd, 0x13, 0xe3, 0x71, 0x4f, 0x8c,
	0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x26, 0xc5, 0x67, 0x69, 0x02, 0x00, 0x00,
}

func (m *CommunitySendMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommunitySendMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommunitySendMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entities) > 0 {
		for iNdEx := len(m.Entities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintChatCommunity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	i--
	if m.ClearDraft {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x38
	i = encodeVarintChatCommunity(dAtA, i, uint64(m.ReplyTo))
	i--
	dAtA[i] = 0x30
	i -= len(m.Body)
	copy(dAtA[i:], m.Body)
	i = encodeVarintChatCommunity(dAtA, i, uint64(len(m.Body)))
	i--
	dAtA[i] = 0x2a
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		{
			size, err := m.Peer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChatCommunity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i = encodeVarintChatCommunity(dAtA, i, uint64(m.RandomID))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *CommunitySendMedia) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommunitySendMedia) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommunitySendMedia) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i--
	if m.ClearDraft {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x30
	i = encodeVarintChatCommunity(dAtA, i, uint64(m.ReplyTo))
	i--
	dAtA[i] = 0x28
	if m.MediaData != nil {
		i -= len(m.MediaData)
		copy(dAtA[i:], m.MediaData)
		i = encodeVarintChatCommunity(dAtA, i, uint64(len(m.MediaData)))
		i--
		dAtA[i] = 0x22
	}
	i = encodeVarintChatCommunity(dAtA, i, uint64(m.MediaType))
	i--
	dAtA[i] = 0x18
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		{
			size, err := m.Peer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChatCommunity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i = encodeVarintChatCommunity(dAtA, i, uint64(m.RandomID))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func encodeVarintChatCommunity(dAtA []byte, offset int, v uint64) int {
	offset -= sovChatCommunity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CommunitySendMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovChatCommunity(uint64(m.RandomID))
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovChatCommunity(uint64(l))
	}
	l = len(m.Body)
	n += 1 + l + sovChatCommunity(uint64(l))
	n += 1 + sovChatCommunity(uint64(m.ReplyTo))
	n += 2
	if len(m.Entities) > 0 {
		for _, e := range m.Entities {
			l = e.Size()
			n += 1 + l + sovChatCommunity(uint64(l))
		}
	}
	return n
}

func (m *CommunitySendMedia) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovChatCommunity(uint64(m.RandomID))
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovChatCommunity(uint64(l))
	}
	n += 1 + sovChatCommunity(uint64(m.MediaType))
	if m.MediaData != nil {
		l = len(m.MediaData)
		n += 1 + l + sovChatCommunity(uint64(l))
	}
	n += 1 + sovChatCommunity(uint64(m.ReplyTo))
	n += 2
	return n
}

func sovChatCommunity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChatCommunity(x uint64) (n int) {
	return sovChatCommunity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CommunitySendMessage) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChatCommunity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommunitySendMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommunitySendMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomID", wireType)
			}
			m.RandomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RandomID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChatCommunity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChatCommunity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplyTo", wireType)
			}
			m.ReplyTo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplyTo |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClearDraft", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ClearDraft = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChatCommunity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entities = append(m.Entities, &MessageEntity{})
			if err := m.Entities[len(m.Entities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChatCommunity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("RandomID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Body")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommunitySendMedia) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChatCommunity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommunitySendMedia: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommunitySendMedia: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomID", wireType)
			}
			m.RandomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RandomID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChatCommunity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MediaType", wireType)
			}
			m.MediaType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MediaType |= InputMediaType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MediaData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthChatCommunity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MediaData = append(m.MediaData[:0], dAtA[iNdEx:postIndex]...)
			if m.MediaData == nil {
				m.MediaData = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplyTo", wireType)
			}
			m.ReplyTo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplyTo |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClearDraft", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ClearDraft = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipChatCommunity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthChatCommunity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("RandomID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("MediaType")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("MediaData")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChatCommunity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChatCommunity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChatCommunity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChatCommunity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChatCommunity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChatCommunity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChatCommunity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChatCommunity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChatCommunity = fmt.Errorf("proto: unexpected end of group")
)
