// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: admin.api.proto

package msg

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AdminPrivilege
type AdminPrivilege int32

const (
	PrivilegeNone       AdminPrivilege = 0
	PrivilegeAdmin      AdminPrivilege = 1
	PrivilegeSuperAdmin AdminPrivilege = 2
)

var AdminPrivilege_name = map[int32]string{
	0: "PrivilegeNone",
	1: "PrivilegeAdmin",
	2: "PrivilegeSuperAdmin",
}

var AdminPrivilege_value = map[string]int32{
	"PrivilegeNone":       0,
	"PrivilegeAdmin":      1,
	"PrivilegeSuperAdmin": 2,
}

func (x AdminPrivilege) Enum() *AdminPrivilege {
	p := new(AdminPrivilege)
	*p = x
	return p
}

func (x AdminPrivilege) String() string {
	return proto.EnumName(AdminPrivilege_name, int32(x))
}

func (x *AdminPrivilege) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdminPrivilege_value, data, "AdminPrivilege")
	if err != nil {
		return err
	}
	*x = AdminPrivilege(value)
	return nil
}

func (AdminPrivilege) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{0}
}

// AdminSetWelcomeMessage
// @Function
// @Return: Bool
type AdminSetWelcomeMessage struct {
	AccessToken string `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
	Lang        string `protobuf:"bytes,2,req,name=Lang" json:"Lang"`
	Template    string `protobuf:"bytes,3,req,name=Template" json:"Template"`
}

func (m *AdminSetWelcomeMessage) Reset()         { *m = AdminSetWelcomeMessage{} }
func (m *AdminSetWelcomeMessage) String() string { return proto.CompactTextString(m) }
func (*AdminSetWelcomeMessage) ProtoMessage()    {}
func (*AdminSetWelcomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{0}
}
func (m *AdminSetWelcomeMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminSetWelcomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminSetWelcomeMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminSetWelcomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminSetWelcomeMessage.Merge(m, src)
}
func (m *AdminSetWelcomeMessage) XXX_Size() int {
	return m.Size()
}
func (m *AdminSetWelcomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminSetWelcomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AdminSetWelcomeMessage proto.InternalMessageInfo

func (m *AdminSetWelcomeMessage) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AdminSetWelcomeMessage) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *AdminSetWelcomeMessage) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

// AdminGetWelcomeMessage
// @Function
// @Return: WelcomeMessagesMany
type AdminGetWelcomeMessages struct {
	AccessToken string `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
}

func (m *AdminGetWelcomeMessages) Reset()         { *m = AdminGetWelcomeMessages{} }
func (m *AdminGetWelcomeMessages) String() string { return proto.CompactTextString(m) }
func (*AdminGetWelcomeMessages) ProtoMessage()    {}
func (*AdminGetWelcomeMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{1}
}
func (m *AdminGetWelcomeMessages) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminGetWelcomeMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminGetWelcomeMessages.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminGetWelcomeMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetWelcomeMessages.Merge(m, src)
}
func (m *AdminGetWelcomeMessages) XXX_Size() int {
	return m.Size()
}
func (m *AdminGetWelcomeMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetWelcomeMessages.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetWelcomeMessages proto.InternalMessageInfo

func (m *AdminGetWelcomeMessages) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// AdminSetPushProvider
// @Function
// @Return: Bool
type AdminSetPushProvider struct {
	AccessToken string        `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
	Provider    *PushProvider `protobuf:"bytes,2,req,name=Provider" json:"Provider,omitempty"`
}

func (m *AdminSetPushProvider) Reset()         { *m = AdminSetPushProvider{} }
func (m *AdminSetPushProvider) String() string { return proto.CompactTextString(m) }
func (*AdminSetPushProvider) ProtoMessage()    {}
func (*AdminSetPushProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{2}
}
func (m *AdminSetPushProvider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminSetPushProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminSetPushProvider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminSetPushProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminSetPushProvider.Merge(m, src)
}
func (m *AdminSetPushProvider) XXX_Size() int {
	return m.Size()
}
func (m *AdminSetPushProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminSetPushProvider.DiscardUnknown(m)
}

var xxx_messageInfo_AdminSetPushProvider proto.InternalMessageInfo

func (m *AdminSetPushProvider) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AdminSetPushProvider) GetProvider() *PushProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

// AdminGetPushProvider
// @Function
// @Return: PushProvidersMany
type AdminGetPushProviders struct {
	AccessToken string `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
}

func (m *AdminGetPushProviders) Reset()         { *m = AdminGetPushProviders{} }
func (m *AdminGetPushProviders) String() string { return proto.CompactTextString(m) }
func (*AdminGetPushProviders) ProtoMessage()    {}
func (*AdminGetPushProviders) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{3}
}
func (m *AdminGetPushProviders) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminGetPushProviders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminGetPushProviders.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminGetPushProviders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetPushProviders.Merge(m, src)
}
func (m *AdminGetPushProviders) XXX_Size() int {
	return m.Size()
}
func (m *AdminGetPushProviders) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetPushProviders.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetPushProviders proto.InternalMessageInfo

func (m *AdminGetPushProviders) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// AdminSetVersion
// @Function
// @Return: Bool
type AdminSetVersion struct {
	AccessToken string   `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
	Version     *Version `protobuf:"bytes,2,req,name=Version" json:"Version,omitempty"`
}

func (m *AdminSetVersion) Reset()         { *m = AdminSetVersion{} }
func (m *AdminSetVersion) String() string { return proto.CompactTextString(m) }
func (*AdminSetVersion) ProtoMessage()    {}
func (*AdminSetVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{4}
}
func (m *AdminSetVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminSetVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminSetVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminSetVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminSetVersion.Merge(m, src)
}
func (m *AdminSetVersion) XXX_Size() int {
	return m.Size()
}
func (m *AdminSetVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminSetVersion.DiscardUnknown(m)
}

var xxx_messageInfo_AdminSetVersion proto.InternalMessageInfo

func (m *AdminSetVersion) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AdminSetVersion) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// AdminGetVersions
// @Function
// @Return: VersionsMany
type AdminGetVersions struct {
	AccessToken string `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
}

func (m *AdminGetVersions) Reset()         { *m = AdminGetVersions{} }
func (m *AdminGetVersions) String() string { return proto.CompactTextString(m) }
func (*AdminGetVersions) ProtoMessage()    {}
func (*AdminGetVersions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{5}
}
func (m *AdminGetVersions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminGetVersions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminGetVersions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminGetVersions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetVersions.Merge(m, src)
}
func (m *AdminGetVersions) XXX_Size() int {
	return m.Size()
}
func (m *AdminGetVersions) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetVersions.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetVersions proto.InternalMessageInfo

func (m *AdminGetVersions) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// AdminSetToken
// @Function
// @Return: AdminToken
type AdminSetToken struct {
	AccessToken string         `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
	Privilege   AdminPrivilege `protobuf:"varint,2,req,name=Privilege,enum=msg.AdminPrivilege" json:"Privilege"`
}

func (m *AdminSetToken) Reset()         { *m = AdminSetToken{} }
func (m *AdminSetToken) String() string { return proto.CompactTextString(m) }
func (*AdminSetToken) ProtoMessage()    {}
func (*AdminSetToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{6}
}
func (m *AdminSetToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminSetToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminSetToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminSetToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminSetToken.Merge(m, src)
}
func (m *AdminSetToken) XXX_Size() int {
	return m.Size()
}
func (m *AdminSetToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminSetToken.DiscardUnknown(m)
}

var xxx_messageInfo_AdminSetToken proto.InternalMessageInfo

func (m *AdminSetToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AdminSetToken) GetPrivilege() AdminPrivilege {
	if m != nil {
		return m.Privilege
	}
	return PrivilegeNone
}

// AdminDeleteToken
// @Function
// @Return: Bool
type AdminDeleteToken struct {
	AccessToken  string `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
	DeletedToken string `protobuf:"bytes,2,req,name=DeletedToken" json:"DeletedToken"`
}

func (m *AdminDeleteToken) Reset()         { *m = AdminDeleteToken{} }
func (m *AdminDeleteToken) String() string { return proto.CompactTextString(m) }
func (*AdminDeleteToken) ProtoMessage()    {}
func (*AdminDeleteToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{7}
}
func (m *AdminDeleteToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminDeleteToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminDeleteToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminDeleteToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDeleteToken.Merge(m, src)
}
func (m *AdminDeleteToken) XXX_Size() int {
	return m.Size()
}
func (m *AdminDeleteToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDeleteToken.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDeleteToken proto.InternalMessageInfo

func (m *AdminDeleteToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AdminDeleteToken) GetDeletedToken() string {
	if m != nil {
		return m.DeletedToken
	}
	return ""
}

// AdminReserveUsername
// @Function
// @Return: Bool
type AdminReserveUsername struct {
	AccessToken string   `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
	Usernames   []string `protobuf:"bytes,2,rep,name=Usernames" json:"Usernames,omitempty"`
	Delete      bool     `protobuf:"varint,3,req,name=Delete" json:"Delete"`
}

func (m *AdminReserveUsername) Reset()         { *m = AdminReserveUsername{} }
func (m *AdminReserveUsername) String() string { return proto.CompactTextString(m) }
func (*AdminReserveUsername) ProtoMessage()    {}
func (*AdminReserveUsername) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{8}
}
func (m *AdminReserveUsername) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminReserveUsername) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminReserveUsername.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminReserveUsername) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminReserveUsername.Merge(m, src)
}
func (m *AdminReserveUsername) XXX_Size() int {
	return m.Size()
}
func (m *AdminReserveUsername) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminReserveUsername.DiscardUnknown(m)
}

var xxx_messageInfo_AdminReserveUsername proto.InternalMessageInfo

func (m *AdminReserveUsername) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AdminReserveUsername) GetUsernames() []string {
	if m != nil {
		return m.Usernames
	}
	return nil
}

func (m *AdminReserveUsername) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

// AdminGetReservedUsernames
// @Function
// @Return: ReservedUsername
type AdminGetReservedUsernames struct {
	AccessToken string `protobuf:"bytes,1,req,name=AccessToken" json:"AccessToken"`
}

func (m *AdminGetReservedUsernames) Reset()         { *m = AdminGetReservedUsernames{} }
func (m *AdminGetReservedUsernames) String() string { return proto.CompactTextString(m) }
func (*AdminGetReservedUsernames) ProtoMessage()    {}
func (*AdminGetReservedUsernames) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{9}
}
func (m *AdminGetReservedUsernames) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminGetReservedUsernames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminGetReservedUsernames.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminGetReservedUsernames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetReservedUsernames.Merge(m, src)
}
func (m *AdminGetReservedUsernames) XXX_Size() int {
	return m.Size()
}
func (m *AdminGetReservedUsernames) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetReservedUsernames.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetReservedUsernames proto.InternalMessageInfo

func (m *AdminGetReservedUsernames) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// AdminToken
type AdminToken struct {
	Privilege AdminPrivilege `protobuf:"varint,1,req,name=Privilege,enum=msg.AdminPrivilege" json:"Privilege"`
	Token     string         `protobuf:"bytes,2,req,name=Token" json:"Token"`
}

func (m *AdminToken) Reset()         { *m = AdminToken{} }
func (m *AdminToken) String() string { return proto.CompactTextString(m) }
func (*AdminToken) ProtoMessage()    {}
func (*AdminToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{10}
}
func (m *AdminToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminToken.Merge(m, src)
}
func (m *AdminToken) XXX_Size() int {
	return m.Size()
}
func (m *AdminToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminToken.DiscardUnknown(m)
}

var xxx_messageInfo_AdminToken proto.InternalMessageInfo

func (m *AdminToken) GetPrivilege() AdminPrivilege {
	if m != nil {
		return m.Privilege
	}
	return PrivilegeNone
}

func (m *AdminToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// WelcomeMessagesMany
type WelcomeMessagesMany struct {
	Messages []*WelcomeMessage `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
	Count    int32             `protobuf:"varint,2,req,name=Count" json:"Count"`
}

func (m *WelcomeMessagesMany) Reset()         { *m = WelcomeMessagesMany{} }
func (m *WelcomeMessagesMany) String() string { return proto.CompactTextString(m) }
func (*WelcomeMessagesMany) ProtoMessage()    {}
func (*WelcomeMessagesMany) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{11}
}
func (m *WelcomeMessagesMany) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WelcomeMessagesMany) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WelcomeMessagesMany.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WelcomeMessagesMany) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeMessagesMany.Merge(m, src)
}
func (m *WelcomeMessagesMany) XXX_Size() int {
	return m.Size()
}
func (m *WelcomeMessagesMany) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeMessagesMany.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeMessagesMany proto.InternalMessageInfo

func (m *WelcomeMessagesMany) GetMessages() []*WelcomeMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *WelcomeMessagesMany) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// VersionsMany
type VersionsMany struct {
	Versions []*Version `protobuf:"bytes,1,rep,name=Versions" json:"Versions,omitempty"`
	Count    int32      `protobuf:"varint,2,req,name=Count" json:"Count"`
}

func (m *VersionsMany) Reset()         { *m = VersionsMany{} }
func (m *VersionsMany) String() string { return proto.CompactTextString(m) }
func (*VersionsMany) ProtoMessage()    {}
func (*VersionsMany) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{12}
}
func (m *VersionsMany) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionsMany) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VersionsMany.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VersionsMany) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionsMany.Merge(m, src)
}
func (m *VersionsMany) XXX_Size() int {
	return m.Size()
}
func (m *VersionsMany) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionsMany.DiscardUnknown(m)
}

var xxx_messageInfo_VersionsMany proto.InternalMessageInfo

func (m *VersionsMany) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *VersionsMany) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// PushProvidersMany
type PushProvidersMany struct {
	Providers []*PushProvider `protobuf:"bytes,1,rep,name=Providers" json:"Providers,omitempty"`
	Count     int32           `protobuf:"varint,2,req,name=Count" json:"Count"`
}

func (m *PushProvidersMany) Reset()         { *m = PushProvidersMany{} }
func (m *PushProvidersMany) String() string { return proto.CompactTextString(m) }
func (*PushProvidersMany) ProtoMessage()    {}
func (*PushProvidersMany) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cd753a9a0a622d5, []int{13}
}
func (m *PushProvidersMany) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushProvidersMany) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushProvidersMany.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushProvidersMany) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushProvidersMany.Merge(m, src)
}
func (m *PushProvidersMany) XXX_Size() int {
	return m.Size()
}
func (m *PushProvidersMany) XXX_DiscardUnknown() {
	xxx_messageInfo_PushProvidersMany.DiscardUnknown(m)
}

var xxx_messageInfo_PushProvidersMany proto.InternalMessageInfo

func (m *PushProvidersMany) GetProviders() []*PushProvider {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *PushProvidersMany) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("msg.AdminPrivilege", AdminPrivilege_name, AdminPrivilege_value)
	proto.RegisterType((*AdminSetWelcomeMessage)(nil), "msg.AdminSetWelcomeMessage")
	proto.RegisterType((*AdminGetWelcomeMessages)(nil), "msg.AdminGetWelcomeMessages")
	proto.RegisterType((*AdminSetPushProvider)(nil), "msg.AdminSetPushProvider")
	proto.RegisterType((*AdminGetPushProviders)(nil), "msg.AdminGetPushProviders")
	proto.RegisterType((*AdminSetVersion)(nil), "msg.AdminSetVersion")
	proto.RegisterType((*AdminGetVersions)(nil), "msg.AdminGetVersions")
	proto.RegisterType((*AdminSetToken)(nil), "msg.AdminSetToken")
	proto.RegisterType((*AdminDeleteToken)(nil), "msg.AdminDeleteToken")
	proto.RegisterType((*AdminReserveUsername)(nil), "msg.AdminReserveUsername")
	proto.RegisterType((*AdminGetReservedUsernames)(nil), "msg.AdminGetReservedUsernames")
	proto.RegisterType((*AdminToken)(nil), "msg.AdminToken")
	proto.RegisterType((*WelcomeMessagesMany)(nil), "msg.WelcomeMessagesMany")
	proto.RegisterType((*VersionsMany)(nil), "msg.VersionsMany")
	proto.RegisterType((*PushProvidersMany)(nil), "msg.PushProvidersMany")
}

func init() { proto.RegisterFile("admin.api.proto", fileDescriptor_2cd753a9a0a622d5) }

var fileDescriptor_2cd753a9a0a622d5 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xb5, 0x93, 0x16, 0x92, 0x49, 0x9a, 0x26, 0x1b, 0xa0, 0x26, 0x8a, 0x4c, 0xb4, 0x87, 0x2a,
	0x42, 0x6a, 0x22, 0xf5, 0x82, 0xc4, 0x05, 0xa5, 0x45, 0xe2, 0x42, 0x51, 0xe4, 0x06, 0xb8, 0xe2,
	0xc4, 0x83, 0x6b, 0x11, 0x7b, 0x2d, 0xaf, 0x1d, 0x09, 0xc4, 0x47, 0xf0, 0x59, 0x3d, 0xe6, 0xc8,
	0x09, 0x41, 0xf2, 0x23, 0xa8, 0xeb, 0x5d, 0xc7, 0x2e, 0x55, 0x65, 0x6e, 0x99, 0x37, 0x6f, 0xde,
	0x7b, 0x9e, 0xcc, 0xc2, 0xa1, 0xed, 0xf8, 0x5e, 0x30, 0xb2, 0x43, 0x6f, 0x14, 0x46, 0x2c, 0x66,
	0xa4, 0xea, 0x73, 0xb7, 0x77, 0xe2, 0x7a, 0xf1, 0x55, 0x32, 0x1f, 0x2d, 0x98, 0x3f, 0x76, 0x99,
	0xcb, 0xc6, 0xa2, 0x37, 0x4f, 0x3e, 0x8b, 0x4a, 0x14, 0xe2, 0x57, 0x3a, 0xd3, 0x6b, 0xa4, 0x22,
	0xa2, 0xa0, 0xdf, 0xe1, 0xc9, 0xe4, 0xa6, 0xbc, 0xc4, 0xf8, 0x23, 0x2e, 0x17, 0xcc, 0xc7, 0x0b,
	0xe4, 0xdc, 0x76, 0x91, 0x1c, 0x43, 0x63, 0xb2, 0x58, 0x20, 0xe7, 0x33, 0xf6, 0x05, 0x03, 0x43,
	0x1f, 0x54, 0x86, 0xf5, 0xb3, 0xbd, 0xeb, 0x5f, 0xcf, 0x34, 0x2b, 0xdf, 0x20, 0x06, 0xec, 0xbd,
	0xb5, 0x03, 0xd7, 0xa8, 0xe4, 0x08, 0x02, 0x21, 0x03, 0xa8, 0xcd, 0xd0, 0x0f, 0x97, 0x76, 0x8c,
	0x46, 0x35, 0xd7, 0xcd, 0x50, 0x3a, 0x81, 0x23, 0xe1, 0xfe, 0xe6, 0xb6, 0x3b, 0x2f, 0x6b, 0x4f,
	0x7d, 0x78, 0xa4, 0x3e, 0x60, 0x9a, 0xf0, 0xab, 0x69, 0xc4, 0x56, 0x9e, 0x83, 0x51, 0xe9, 0xf8,
	0x27, 0x50, 0x53, 0x33, 0xe2, 0x13, 0x1a, 0xa7, 0x9d, 0x91, 0xcf, 0xdd, 0x51, 0x5e, 0xcc, 0xca,
	0x28, 0xf4, 0x15, 0x3c, 0x56, 0x89, 0xf3, 0x8c, 0xf2, 0x79, 0x6d, 0x38, 0x54, 0x79, 0x3f, 0x60,
	0xc4, 0x3d, 0x16, 0x94, 0x8e, 0x7a, 0x0c, 0x0f, 0xe5, 0x88, 0x4c, 0xda, 0x14, 0x49, 0x25, 0x66,
	0xa9, 0x26, 0x7d, 0x09, 0x6d, 0x95, 0x51, 0x42, 0xe5, 0xe3, 0x85, 0x70, 0xa0, 0xe2, 0x29, 0xd3,
	0x72, 0xe1, 0x5e, 0x40, 0x7d, 0x1a, 0x79, 0x2b, 0x6f, 0x89, 0x2e, 0x8a, 0x78, 0xad, 0xd3, 0xae,
	0x88, 0x27, 0xe4, 0xb2, 0x96, 0x1c, 0xdd, 0x71, 0xa9, 0x23, 0xd3, 0xbe, 0xc6, 0x25, 0xc6, 0xf8,
	0x7f, 0xa6, 0x43, 0x68, 0xa6, 0x63, 0x4e, 0x4a, 0xcc, 0xdf, 0x60, 0xa1, 0x43, 0xbf, 0xc9, 0x33,
	0xb1, 0x90, 0x63, 0xb4, 0xc2, 0xf7, 0x1c, 0xa3, 0xc0, 0xf6, 0xcb, 0x5f, 0x79, 0x1f, 0xea, 0x6a,
	0x86, 0x1b, 0x95, 0x41, 0x75, 0x58, 0xb7, 0x76, 0x00, 0xe9, 0xc3, 0x83, 0xd4, 0x4d, 0xdc, 0x79,
	0x4d, 0x0a, 0x48, 0x8c, 0x9e, 0xc3, 0x53, 0xf5, 0x7f, 0x48, 0x7b, 0x67, 0x37, 0x5a, 0xfe, 0x6e,
	0x40, 0x88, 0xdc, 0xb1, 0x6d, 0xbd, 0xfc, 0xb6, 0x49, 0x0f, 0xf6, 0xff, 0x5d, 0x55, 0x0a, 0xd1,
	0x39, 0x74, 0x6f, 0xbd, 0xc2, 0x0b, 0x3b, 0xf8, 0x4a, 0xc6, 0x50, 0x53, 0xb5, 0xa1, 0x0f, 0xaa,
	0xc3, 0x86, 0xb4, 0x2a, 0x72, 0xad, 0x8c, 0x74, 0xe3, 0x71, 0xce, 0x92, 0x20, 0x16, 0x1e, 0xfb,
	0xca, 0x43, 0x40, 0x74, 0x06, 0x4d, 0x75, 0x93, 0x42, 0x7c, 0x08, 0x35, 0x55, 0x4b, 0xf1, 0xe2,
	0x51, 0x67, 0xdd, 0x7b, 0x55, 0x3f, 0x41, 0xa7, 0xf0, 0x1a, 0x65, 0xee, 0x7a, 0x06, 0x48, 0xed,
	0x3b, 0x9e, 0xf6, 0x8e, 0x73, 0x9f, 0xc3, 0xf3, 0x29, 0xb4, 0x8a, 0xab, 0x25, 0x1d, 0x38, 0xc8,
	0x8a, 0x77, 0x2c, 0xc0, 0xb6, 0x46, 0x08, 0xb4, 0x32, 0x48, 0xb0, 0xdb, 0x3a, 0x39, 0x82, 0x6e,
	0x86, 0x5d, 0x26, 0x21, 0x46, 0x69, 0xa3, 0x72, 0xd6, 0x5f, 0xff, 0x31, 0xb5, 0xeb, 0x8d, 0xa9,
	0xaf, 0x37, 0xa6, 0xfe, 0x7b, 0x63, 0xea, 0x3f, 0xb6, 0xa6, 0xb6, 0xde, 0x9a, 0xda, 0xcf, 0xad,
	0xa9, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x70, 0xb5, 0x51, 0xfa, 0xea, 0x05, 0x00, 0x00,
}

func (m *AdminSetWelcomeMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminSetWelcomeMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminSetWelcomeMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Template)
	copy(dAtA[i:], m.Template)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.Template)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Lang)
	copy(dAtA[i:], m.Lang)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.Lang)))
	i--
	dAtA[i] = 0x12
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminGetWelcomeMessages) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminGetWelcomeMessages) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminGetWelcomeMessages) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminSetPushProvider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminSetPushProvider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminSetPushProvider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Provider == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Provider")
	} else {
		{
			size, err := m.Provider.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAdminApi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminGetPushProviders) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminGetPushProviders) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminGetPushProviders) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminSetVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminSetVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminSetVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Version")
	} else {
		{
			size, err := m.Version.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAdminApi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminGetVersions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminGetVersions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminGetVersions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminSetToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminSetToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminSetToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintAdminApi(dAtA, i, uint64(m.Privilege))
	i--
	dAtA[i] = 0x10
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminDeleteToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminDeleteToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminDeleteToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.DeletedToken)
	copy(dAtA[i:], m.DeletedToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.DeletedToken)))
	i--
	dAtA[i] = 0x12
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminReserveUsername) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminReserveUsername) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminReserveUsername) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i--
	if m.Delete {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x18
	if len(m.Usernames) > 0 {
		for iNdEx := len(m.Usernames) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Usernames[iNdEx])
			copy(dAtA[i:], m.Usernames[iNdEx])
			i = encodeVarintAdminApi(dAtA, i, uint64(len(m.Usernames[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminGetReservedUsernames) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminGetReservedUsernames) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminGetReservedUsernames) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.AccessToken)
	copy(dAtA[i:], m.AccessToken)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.AccessToken)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AdminToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Token)
	copy(dAtA[i:], m.Token)
	i = encodeVarintAdminApi(dAtA, i, uint64(len(m.Token)))
	i--
	dAtA[i] = 0x12
	i = encodeVarintAdminApi(dAtA, i, uint64(m.Privilege))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *WelcomeMessagesMany) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WelcomeMessagesMany) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WelcomeMessagesMany) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintAdminApi(dAtA, i, uint64(m.Count))
	i--
	dAtA[i] = 0x10
	if len(m.Messages) > 0 {
		for iNdEx := len(m.Messages) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Messages[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAdminApi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *VersionsMany) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionsMany) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VersionsMany) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintAdminApi(dAtA, i, uint64(m.Count))
	i--
	dAtA[i] = 0x10
	if len(m.Versions) > 0 {
		for iNdEx := len(m.Versions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Versions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAdminApi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PushProvidersMany) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushProvidersMany) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushProvidersMany) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintAdminApi(dAtA, i, uint64(m.Count))
	i--
	dAtA[i] = 0x10
	if len(m.Providers) > 0 {
		for iNdEx := len(m.Providers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Providers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAdminApi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintAdminApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovAdminApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AdminSetWelcomeMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	l = len(m.Lang)
	n += 1 + l + sovAdminApi(uint64(l))
	l = len(m.Template)
	n += 1 + l + sovAdminApi(uint64(l))
	return n
}

func (m *AdminGetWelcomeMessages) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	return n
}

func (m *AdminSetPushProvider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	if m.Provider != nil {
		l = m.Provider.Size()
		n += 1 + l + sovAdminApi(uint64(l))
	}
	return n
}

func (m *AdminGetPushProviders) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	return n
}

func (m *AdminSetVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	if m.Version != nil {
		l = m.Version.Size()
		n += 1 + l + sovAdminApi(uint64(l))
	}
	return n
}

func (m *AdminGetVersions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	return n
}

func (m *AdminSetToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	n += 1 + sovAdminApi(uint64(m.Privilege))
	return n
}

func (m *AdminDeleteToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	l = len(m.DeletedToken)
	n += 1 + l + sovAdminApi(uint64(l))
	return n
}

func (m *AdminReserveUsername) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	if len(m.Usernames) > 0 {
		for _, s := range m.Usernames {
			l = len(s)
			n += 1 + l + sovAdminApi(uint64(l))
		}
	}
	n += 2
	return n
}

func (m *AdminGetReservedUsernames) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	n += 1 + l + sovAdminApi(uint64(l))
	return n
}

func (m *AdminToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAdminApi(uint64(m.Privilege))
	l = len(m.Token)
	n += 1 + l + sovAdminApi(uint64(l))
	return n
}

func (m *WelcomeMessagesMany) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for _, e := range m.Messages {
			l = e.Size()
			n += 1 + l + sovAdminApi(uint64(l))
		}
	}
	n += 1 + sovAdminApi(uint64(m.Count))
	return n
}

func (m *VersionsMany) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Versions) > 0 {
		for _, e := range m.Versions {
			l = e.Size()
			n += 1 + l + sovAdminApi(uint64(l))
		}
	}
	n += 1 + sovAdminApi(uint64(m.Count))
	return n
}

func (m *PushProvidersMany) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Providers) > 0 {
		for _, e := range m.Providers {
			l = e.Size()
			n += 1 + l + sovAdminApi(uint64(l))
		}
	}
	n += 1 + sovAdminApi(uint64(m.Count))
	return n
}

func sovAdminApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAdminApi(x uint64) (n int) {
	return sovAdminApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AdminSetWelcomeMessage) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminSetWelcomeMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminSetWelcomeMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lang", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lang = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Template", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Template = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Lang")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Template")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminGetWelcomeMessages) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminGetWelcomeMessages: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminGetWelcomeMessages: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminSetPushProvider) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminSetPushProvider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminSetPushProvider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Provider == nil {
				m.Provider = &PushProvider{}
			}
			if err := m.Provider.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Provider")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminGetPushProviders) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminGetPushProviders: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminGetPushProviders: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminSetVersion) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminSetVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminSetVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Version == nil {
				m.Version = &Version{}
			}
			if err := m.Version.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Version")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminGetVersions) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminGetVersions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminGetVersions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminSetToken) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminSetToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminSetToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Privilege", wireType)
			}
			m.Privilege = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Privilege |= AdminPrivilege(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Privilege")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminDeleteToken) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminDeleteToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminDeleteToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeletedToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("DeletedToken")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminReserveUsername) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminReserveUsername: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminReserveUsername: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Usernames", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Usernames = append(m.Usernames, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Delete = bool(v != 0)
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Delete")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminGetReservedUsernames) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminGetReservedUsernames: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminGetReservedUsernames: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("AccessToken")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminToken) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Privilege", wireType)
			}
			m.Privilege = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Privilege |= AdminPrivilege(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Privilege")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Token")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WelcomeMessagesMany) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WelcomeMessagesMany: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WelcomeMessagesMany: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, &WelcomeMessage{})
			if err := m.Messages[len(m.Messages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Count")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VersionsMany) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionsMany: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionsMany: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Versions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Versions = append(m.Versions, &Version{})
			if err := m.Versions[len(m.Versions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Count")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PushProvidersMany) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushProvidersMany: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushProvidersMany: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdminApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdminApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Providers = append(m.Providers, &PushProvider{})
			if err := m.Providers[len(m.Providers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Count")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAdminApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAdminApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdminApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAdminApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAdminApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAdminApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAdminApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAdminApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAdminApi = fmt.Errorf("proto: unexpected end of group")
)
