// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bot.api.proto

package msg

import (
	fmt "fmt"
	pbytes "github.com/gobwas/pool/pbytes"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	sync "sync"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

const C_StartBot int64 = 3294108684

type poolStartBot struct {
	pool sync.Pool
}

func (p poolStartBot) Get() *StartBot {
	x, ok := p.pool.Get().(*StartBot)
	if !ok {
		return &StartBot{}
	}
	return x
}

func (p poolStartBot) Put(x *StartBot) {
	p.pool.Put(x)
}

var PoolStartBot = poolStartBot{}

func ResultStartBot(out *MessageEnvelope, res *StartBot) {
	out.Constructor = C_StartBot
	pbytes.Put(out.Message)
	out.Message = pbytes.GetLen(res.Size())
	res.MarshalTo(out.Message)
}

func init() {
	ConstructorNames[3294108684] = "StartBot"
}
